In [1]:
import numpy as np

In [4]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [5]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
mean_a = np.mean(a,axis=0)

In [7]:
mean_a

array([2. , 8.4])

In [10]:
a_centered = np.subtract(a,mean_a)

In [11]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [52]:
a_centered_sp = np.dot(a_centered[0:5,0],a_centered[0:5,1])

In [53]:
a_centered_sp

8.0

In [54]:
cov = a_centered_sp / 4

In [55]:
cov

2.0