Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?
7. Вертикально соединить массивы a и b. a - двумерный массив из нулей, 
число строк которого больше 1 и на 1 меньше, чем число строк двумерного 
массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.
8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 
4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B?
Получится ли вычислить обратную матрицу для матрицы B и почему?
9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. 
Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C.
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.
10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы.
С помощью функции numpy.where, используя матрицу D_inv в качестве маски,
а матрицы B и C - в качестве источников данных,
получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1,
должны быть равны соответствующему элементу матрицы B,
а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0,
должны быть равны соответствующему элементу матрицы C.

In [2]:
a = np.array([i for i in range(12,24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
b = np.arange(12,24)
b

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [4]:
b.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
b.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
b.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [7]:
b.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [8]:
b.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [9]:
b.reshape(3,-1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
b.reshape(-1,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

п.3 нет нельзя, это двумерный массив

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [11]:
b = np.random.randn(3,4)
b

array([[ 1.97928991,  1.8512786 , -0.31309881,  1.32336289],
       [-0.62928722, -0.21504168,  2.14749021, -0.21435543],
       [ 0.63163195, -0.8252675 ,  0.27967677,  0.83114573]])

In [12]:
b.size

12

In [13]:
b.flatten()


array([ 1.97928991,  1.8512786 , -0.31309881,  1.32336289, -0.62928722,
       -0.21504168,  2.14749021, -0.21435543,  0.63163195, -0.8252675 ,
        0.27967677,  0.83114573])

In [14]:
b.size

12

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?


In [15]:
aa = np.arange(20,0,-2)
aa

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [16]:
bb = np.arange(20,1,-2)
bb

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

нет разницы, крайнее правое число не включительно

In [17]:
x = np.zeros((2,2))
z = np.ones((3,2))
x

array([[0., 0.],
       [0., 0.]])

In [18]:
z

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.vstack((x,z))

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 
4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B?
Получится ли вычислить обратную матрицу для матрицы B и почему?


In [20]:
s = np.arange(0,12).reshape(4,3)
s

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
sT = s.transpose()

In [22]:
sT

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [23]:
s.shape[1] == sT.shape[0]

True

In [24]:
z = np.dot(s,sT)
z

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [25]:
z.size

16

матрица не квадратная

9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. 
Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C.
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [26]:
np.random.seed(42)

In [34]:
c = np.random.randint(0,16,16)
c

array([ 7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7,  7,  2,  5])

In [36]:
cr = c.reshape(4,4)
cr

array([[ 7, 12,  4,  6],
       [ 9,  2,  6, 10],
       [10,  7,  4,  3],
       [ 7,  7,  2,  5]])

In [37]:
c10 = cr*10
c10

array([[ 70, 120,  40,  60],
       [ 90,  20,  60, 100],
       [100,  70,  40,  30],
       [ 70,  70,  20,  50]])

In [39]:
cc = c10*z
cc

array([[  350,  1680,   920,  1920],
       [ 1260,  1000,  5160, 12200],
       [ 2300,  6020,  5960,  6360],
       [ 2240,  8540,  4240, 15100]])

In [40]:
np.linalg.det(cc)

51687983199999.96

In [41]:
np.linalg.matrix_rank(cc)

4

In [42]:
cc_inv = np.linalg.inv(cc)

In [43]:
cc_inv

array([[-8.42208012e-03, -4.54879888e-04,  9.57478101e-04,
         1.03512369e-03],
       [ 1.35773454e-03, -7.14572280e-05, -9.41982971e-05,
        -7.52298650e-05],
       [ 1.94889817e-03,  1.89308296e-04, -1.69144150e-05,
        -3.93633776e-04],
       [-6.57564058e-05,  5.47356624e-05, -8.40119450e-05,
         6.57478932e-05]])